# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sample.proto for package 'sample'

require 'grpc'
require 'sample_pb'

module Sample
  module Greeter
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sample.Greeter'

      rpc :Hello, HelloRequest, HelloResponse
    end

    Stub = Service.rpc_stub_class
  end
end
