# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sample.HelloRequest" do
    optional :name, :string, 1
  end
  add_message "sample.HelloResponse" do
    optional :greet, :string, 1
  end
end

module Sample
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.HelloRequest").msgclass
  HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.HelloResponse").msgclass
end
